### ISSUE TITLE
Support multi-site with sidebar icon 

### ISSUE THREAD

**Issue by weotch** [BKWLD/craft-netlify-deploy-status#1]
Consider a Craft instance with multiple Sites that deploy to different Netlify apps.  For instance, a localized where each Craft Site represents a different region and where there is a discrete Netlify app to represent each region.  In this case, the admin would register an incoming webhook in `craft-netlify-deploy-status` for every production Netlify app.  Thus, there would be an incoming webhook for `en-US` and `fr-CA` and so forth.

If a commit is pushed to the repo, a deploy will be triggered on reach regional Netlify app.  Ideally, the sidebar icon will only revert to the non-spinner state when all deploys have finished.  As it's implemented now, what I expect will happen is:

1. `en-US` and `fr-CA` start deploying
2. Most recent activity status is `building` so the icon state changes to spinner.
3. `en-US` finishes deploying, `fr-CA` is still buildinng
4. The most recent activity status is now `published` from `en-US` finishing. Thus the icon drops the spinner status.  However, Netlify _is_ still building the `fr-CA` app.

I think we can solve for this by looping through each incoming webhook and checking their status.  If any registered incoming webhook has a status of "building", then show the spinner.  Otherwise, show the Netlify logo.

**Comment by isaazgarcia** [comment]
This is the function that I use to check if it is deploying.

In short, It searches for the last status of each webhook and then it checks if those statuses are not deployed. And it's also going to check only the statuses if the last hour. So I think this already answers your question...?

https://github.com/BKWLD/craft-netlify-deploy-status/blob/708504cc290f684c3ccdf392da2c701ed88a406e/src/controllers/StatusController.php#L92-L110

**Comment by weotch** [comment]
Oh perf, I think this is what I'm talking about!  Two notes:

1. Why the check on for the last hour?  What's the thinking there?
2. I think [on line 105](https://github.com/BKWLD/craft-netlify-deploy-status/blob/708504cc290f684c3ccdf392da2c701ed88a406e/src/controllers/StatusController.php#L105) we should make the check `state == "building"` (or whatever it is) because we don't want to treat failed status as deploying, right?

**Comment by isaazgarcia** [comment]
> Why the check on for the last hour? What's the thinking there?

Just in case a finished status does not get to the system, so it doesn't. Although this could be overwrited by the next deploy.

> I think on line 105 we should make the check state == "building" (or whatever it is) because we don't want to treat failed status as deploying, right?

That is right, just thought about it after writing that to you. I'll make a PR for that.
